# Generated by Django 4.0.4 on 2022-07-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='go',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='query',
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('dir', models.CharField(blank=True, max_length=50)),
                ('query', models.IntegerField(blank=True, choices=[[0, 'PetShop'], [1, 'Veterinaria'], [2, 'Paseador/Recreación'], [3, 'Guardería'], [4, 'Peluquería']])),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(default='mp.jpg', upload_to='images/profile_image')),
                ('go', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
    ]
