# Generated by Django 4.0.4 on 2022-07-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_alter_local_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='user',
        ),
    ]
